### ISSUE TITLE
[Feature Request] Support a command line argument

### ISSUE THREAD

**Issue by colemar** [ErrorFlynn/ytdlp-interface#116]
I would like to add a _ytdlp-interface_ menu item in [External Application Launcher](https://webextension.org/listing/external-application-button.html).
The intended effect would be that while watching a video with a browser a simple click on the button would start ytdlp-interface with the url already queued.
Better yet, if ytdlp-interface is already running, the url would be added to the queue.

This is currently impossible because ytdlp-interface does not accept arguments:
``ytdlp-interface.exe https://www.youtube.com/watch?v=jgojOn0PaNE``

**Comment by colemar** [comment]
Thank you!
Now downloading last release...
Wonderful, it works!

**Comment by iG8R** [comment]
@ErrorFlynn 
It seems this option no longer works; at least, it doesn't work in version 2.18.

**Comment by ErrorFlynn** [comment]
> [@ErrorFlynn](https://github.com/ErrorFlynn) It seems this option no longer works; at least, it doesn't work in version 2.18.

This should be fixed now in v2.18.1.

**Comment by iG8R** [comment]
@ErrorFlynn Unfortunately, it didn't work - the video address is still not being added to `ytdlp-interface`.

**Comment by ErrorFlynn** [comment]
From my testing (from the command prompt, not using the extension), it works if `ytdlp-interface.exe` is already running. If it's not already running it will start without adding the URL (I'll have to fix that). So if you have that extension installed, you'd have to click the button once to start ytdlp-interface, and then click it again to add the URL. Let me know if that doesn't describe your experience (does it not work at all on your end?)

**Comment by iG8R** [comment]
Initially, I tested it when `ytdlp-interface` wasn't running yet, and, as you mentioned, everything is exactly as you described - `it works if ytdlp-interface.exe is already running. If it's not already running it will start without adding the URL.`
But the thing is that I usually don't leave `ytdlp-interface` running in the background.
